In [2]:
import numpy
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [23]:
import cv2
img = cv2.imread("smallgray.png",0) #0 open in gray scale, 0 to 255
print(img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [25]:
img[2,4] #print pixel

182

In [26]:
for i in img: #print lines
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [27]:
for i in img.flat: #print all the pixels
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [29]:
img2 = numpy.hstack((img,img)) #h for horizontal and v for vertical
print(img2)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [32]:
img3 = numpy.hsplit(img2,5) #will create 5 tiny arrays
print (img3)

[array([[187, 158],
       [198, 125],
       [209, 134]], dtype=uint8), array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8), array([[143, 187],
       [147, 198],
       [182, 209]], dtype=uint8), array([[158, 104],
       [125, 255],
       [134, 255]], dtype=uint8), array([[121, 143],
       [255, 147],
       [ 97, 182]], dtype=uint8)]
